/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author felipecovapacheco
 * Nota: La interfaz Gráfica se hizo en NetBeans.
 */
public class View extends javax.swing.JFrame {
    
    /* Imagen con la que trabajará el app. */
    private BufferedImage imagen;
    /* App para aplicar los filtros. */
    private final App app;
    /* Copia la imagen original con la que se trabajará. */
    private BufferedImage copia;

    /**
     * Clase para probar distintos filtros.
     */
    public View() {
        initComponents();
        /* Para que el panel principal aparezca centrado. */
        this.setLocationRelativeTo(null);
        /* Le quitamos el texto a la etiqueta para poner la imagen ahí. */
        img.setText(null);
        /* Le quitamos el texto a la barra de progreso. */
        progreso.setText(null);
        /* App para modificar la imagen. */
        app = new App();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        img = new javax.swing.JLabel();
        progreso = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        reiniciar = new javax.swing.JMenuItem();
        menu_ajusteDeColor = new javax.swing.JMenu();
        rojo = new javax.swing.JMenuItem();
        verde = new javax.swing.JMenuItem();
        azul = new javax.swing.JMenuItem();
        rgb = new javax.swing.JMenuItem();
        brillo = new javax.swing.JMenuItem();
        azar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        grisesPromedio = new javax.swing.JMenuItem();
        grisesLuma = new javax.swing.JMenuItem();
        grisesDesaturation = new javax.swing.JMenuItem();
        grisesDescomposition = new javax.swing.JMenuItem();
        grisesSingleColor = new javax.swing.JMenuItem();
        grisesShades = new javax.swing.JMenuItem();
        grisesDithering = new javax.swing.JMenuItem();
        sepia = new javax.swing.JMenuItem();
        luzNegra = new javax.swing.JMenuItem();
        menu_mosaicos = new javax.swing.JMenu();
        mosaico = new javax.swing.JMenuItem();
        recursivas = new javax.swing.JMenuItem();
        sopaLetras = new javax.swing.JMenuItem();
        hombresNegro = new javax.swing.JMenuItem();
        recurwsc = new javax.swing.JMenuItem();
        fotomosaicos = new javax.swing.JMenuItem();
        menu_contrastes = new javax.swing.JMenu();
        inverso = new javax.swing.JMenuItem();
        altoContraste = new javax.swing.JMenuItem();
        semitonos = new javax.swing.JMenuItem();
        menu_artisticos = new javax.swing.JMenu();
        att = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        oleobn = new javax.swing.JMenuItem();
        oleocolor = new javax.swing.JMenuItem();
        menu_combinar = new javax.swing.JMenu();
        blending = new javax.swing.JMenuItem();
        menu_iconos = new javax.swing.JMenu();
        favicon = new javax.swing.JMenuItem();
        creadorIconos = new javax.swing.JMenuItem();
        menu_marcaAgua = new javax.swing.JMenu();
        marcaAgua = new javax.swing.JMenuItem();
        menu_rotar = new javax.swing.JMenu();
        rotar = new javax.swing.JMenuItem();
        rotamat = new javax.swing.JMenuItem();
        reduccion = new javax.swing.JMenuItem();
        ampliacion = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        borde = new javax.swing.JMenuItem();
        sharpen = new javax.swing.JMenuItem();
        blur = new javax.swing.JMenuItem();
        motionblur = new javax.swing.JMenuItem();
        promedio = new javax.swing.JMenuItem();
        media = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        losseless = new javax.swing.JMenuItem();
        lossy = new javax.swing.JMenuItem();
        descompresión = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Felipe Shop.");

        img.setText("jLabel1");

        progreso.setEditable(false);
        progreso.setText("jTextField1");

        menu_archivo.setText("Archivo");

        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        menu_archivo.add(abrir);

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        menu_archivo.add(guardar);

        reiniciar.setText("Reiniciar");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });
        menu_archivo.add(reiniciar);

        jMenuBar2.add(menu_archivo);

        menu_ajusteDeColor.setText("Ajuste de color");

        rojo.setText("Filtro Rojo");
        rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojoActionPerformed(evt);
            }
        });
        menu_ajusteDeColor.add(rojo);

        verde.setText("Filtro Verde");
        verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdeActionPerformed(evt);
            }
        });
        menu_ajusteDeColor.add(verde);

        azul.setText("Filtro Azul");
        azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulActionPerformed(evt);
            }
        });
        menu_ajusteDeColor.add(azul);

        rgb.setText("Filtro RGB");
        rgb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgbActionPerformed(evt);
            }
        });
        menu_ajusteDeColor.add(rgb);

        brillo.setText("Filtro Brillo");
        brillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brilloActionPerformed(evt);
            }
        });
        menu_ajusteDeColor.add(brillo);

        azar.setText("Filtro Azar");
        azar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azarActionPerformed(evt);
            }
        });
        menu_ajusteDeColor.add(azar);

        jMenu3.setText("Filtros Escala de Grises");

        grisesPromedio.setText("Filtro Grises \"Average\"");
        grisesPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grisesPromedioActionPerformed(evt);
            }
        });
        jMenu3.add(grisesPromedio);

        grisesLuma.setText("Filtro Grises \"Luma\"");
        grisesLuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grisesLumaActionPerformed(evt);
            }
        });
        jMenu3.add(grisesLuma);

        grisesDesaturation.setText("Filtro Grises \"Desaturation\"");
        grisesDesaturation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grisesDesaturationActionPerformed(evt);
            }
        });
        jMenu3.add(grisesDesaturation);

        grisesDescomposition.setText("Filtro Grises \"Descomposition\"");
        grisesDescomposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grisesDescompositionActionPerformed(evt);
            }
        });
        jMenu3.add(grisesDescomposition);

        grisesSingleColor.setText("Filtro Grises \"Single color\"");
        grisesSingleColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grisesSingleColorActionPerformed(evt);
            }
        });
        jMenu3.add(grisesSingleColor);

        grisesShades.setText("Filtro Grises \"Shades\"");
        grisesShades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grisesShadesActionPerformed(evt);
            }
        });
        jMenu3.add(grisesShades);

        grisesDithering.setText("Filtro Grises \"Dithering\"");
        grisesDithering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grisesDitheringActionPerformed(evt);
            }
        });
        jMenu3.add(grisesDithering);

        menu_ajusteDeColor.add(jMenu3);

        sepia.setText("Filtro Sepia");
        sepia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepiaActionPerformed(evt);
            }
        });
        menu_ajusteDeColor.add(sepia);

        luzNegra.setText("Filtro Luz Negra");
        luzNegra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luzNegraActionPerformed(evt);
            }
        });
        menu_ajusteDeColor.add(luzNegra);

        jMenuBar2.add(menu_ajusteDeColor);

        menu_mosaicos.setText("Mosaicos");

        mosaico.setText("Filtro Mosaico");
        mosaico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mosaicoActionPerformed(evt);
            }
        });
        menu_mosaicos.add(mosaico);

        recursivas.setText("Imágenes Recursivas (Color real)");
        recursivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recursivasActionPerformed(evt);
            }
        });
        menu_mosaicos.add(recursivas);
        
        sopaLetras.setText("Sopa de Letras");
        sopaLetras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sopaLetrasActionPerformed(evt);
            }
        });
        menu_mosaicos.add(sopaLetras);

        hombresNegro.setText("Hombres de Negro");
        hombresNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hombresNegroActionPerformed(evt);
            }
        });
        menu_mosaicos.add(hombresNegro);
        

        recurwsc.setText("Imágenes Recursiva (Web Safe Color)");
        recurwsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recurwscActionPerformed(evt);
            }
        });
        menu_mosaicos.add(recurwsc);

        
        fotomosaicos.setText("Fotomosaicos");
        fotomosaicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotomosaicosActionPerformed(evt);
            }
        });
        menu_mosaicos.add(fotomosaicos);
        
        jMenuBar2.add(menu_mosaicos);
        
        menu_contrastes.setText("Contrastes");
        
        inverso.setText("Filtro Inverso");
        inverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inversoActionPerformed(evt);
            }
        });
        menu_contrastes.add(inverso);

        altoContraste.setText("Filtro Alto Contraste");
        altoContraste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altoContrasteActionPerformed(evt);
            }
        });
        menu_contrastes.add(altoContraste);
        

        semitonos.setText("Filtro Semitonos");
        semitonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semitonosActionPerformed(evt);
            }
        });
        menu_contrastes.add(semitonos);
        
        jMenuBar2.add(menu_contrastes);
        
        menu_artisticos.setText("Artisticos");

        att.setText("Filtro AT&T");
        att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attActionPerformed(evt);
            }
        });
        menu_artisticos.add(att);

        jMenu5.setText("Oleo");

        oleobn.setText("Grises");
        oleobn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oleobnActionPerformed(evt);
            }
        });
        jMenu5.add(oleobn);

        oleocolor.setText("Color");
        oleocolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oleocolorActionPerformed(evt);
            }
        });
        jMenu5.add(oleocolor);

        menu_artisticos.add(jMenu5);

        jMenuBar2.add(menu_artisticos);
        
        menu_combinar.setText("Combinar Imágenes");

        blending.setText("Filtro Blending");
        blending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blendingActionPerformed(evt);
            }
        });
        menu_combinar.add(blending);

        jMenuBar2.add(menu_combinar);

        menu_iconos.setText("Iconos");

        favicon.setText("Favicones");
        menu_iconos.add(favicon);

        creadorIconos.setText("Creador de iconos");
        creadorIconos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creadorIconosActionPerformed(evt);
            }
        });
        menu_iconos.add(creadorIconos);

        jMenuBar2.add(menu_iconos);
        
        menu_marcaAgua.setText("Marca de Agua");

        marcaAgua.setText("Filtro Marca de Agua");
        marcaAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaAguaActionPerformed(evt);
            }
        });
        menu_marcaAgua.add(marcaAgua);

        jMenuBar2.add(menu_marcaAgua);
        
        menu_rotar.setText("Modificar");

        rotar.setText("Filtro Rotar Imagen");
        rotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotarActionPerformed(evt);
            }
        });
        menu_rotar.add(rotar);

        rotamat.setText("Rotar con Matriz");
        rotamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotamatActionPerformed(evt);
            }
        });
        menu_rotar.add(rotamat);

        reduccion.setText("Reducción");
        reduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reduccionActionPerformed(evt);
            }
        });
        menu_rotar.add(reduccion);

        ampliacion.setText("Aplicación");
        ampliacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ampliacionActionPerformed(evt);
            }
        });
        menu_rotar.add(ampliacion);

        jMenuBar2.add(menu_rotar);

        jMenu4.setText("Convolución");

        borde.setText("Borde");
        borde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bordeActionPerformed(evt);
            }
        });
        jMenu4.add(borde);

        sharpen.setText("Sharpen");
        sharpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sharpenActionPerformed(evt);
            }
        });
        jMenu4.add(sharpen);

        blur.setText("Blur");
        blur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blurActionPerformed(evt);
            }
        });
        jMenu4.add(blur);

        motionblur.setText("Motion Blur");
        motionblur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motionblurActionPerformed(evt);
            }
        });
        jMenu4.add(motionblur);

        promedio.setText("Promedio");
        promedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promedioActionPerformed(evt);
            }
        });
        jMenu4.add(promedio);

        media.setText("Media");
        media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediaActionPerformed(evt);
            }
        });
        jMenu4.add(media);

        jMenuBar2.add(jMenu4);

        jMenu6.setText("Compresión");

        jMenu7.setText("Compresión");
        

        losseless.setText("Losseless");
        losseless.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                losselessActionPerformed(evt);
            }
        });
        jMenu7.add(losseless);

        lossy.setText("Lossy");
        lossy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lossyActionPerformed(evt);
            }
        });
        jMenu7.add(lossy);

        jMenu6.add(jMenu7);

        descompresión.setText("Descompresión");
        descompresión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descompresiónActionPerformed(evt);
            }
        });
        jMenu6.add(descompresión);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {                                      
        imagen = app.abreImagen();
        copia = app.copia();
        img.setIcon(new ImageIcon(imagen.getScaledInstance(img.getWidth(), 
                img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Imagen escogida");
    }                                     

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {                                        
        app.guardaImagen();
        progreso.setText("Imagen guardada");
    }                                       

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        reinicia();
        progreso.setText("Cambios deshechos");
    }                                         

    private void rojoActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if (imagen == null)
            return;
        progreso.setText("Espera un momento...");
        img.setIcon(new ImageIcon(app.rojo().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro seleccionado ha sido aplicado");
    }                                    

    private void azulActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        
        img.setIcon(new ImageIcon(app.azul().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
        
    }                                    

    private void verdeActionPerformed(java.awt.event.ActionEvent evt) {                                      
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        img.setIcon(new ImageIcon(app.verde().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                     

    private void rgbActionPerformed(java.awt.event.ActionEvent evt) {                                    
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        int r = sliderRGB("Rojo: ");
        int g = sliderRGB("Verde: ");
        int b = sliderRGB("Azul: ");
        img.setIcon(new ImageIcon(app.rgb(r,g,b).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                   

    private void brilloActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        int s = sliderBrillo();
        img.setIcon(new ImageIcon(app.brillo(s).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                      

    private void azarActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        img.setIcon(new ImageIcon(app.azar().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                    

    private void grisesPromedioActionPerformed(java.awt.event.ActionEvent evt) {                                               
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        img.setIcon(new ImageIcon(app.grisesAverage().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                              

    private void grisesLumaActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        img.setIcon(new ImageIcon(app.grisesLuma().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                          

    private void grisesDesaturationActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        img.setIcon(new ImageIcon(app.grisesDesaturation().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                                  

    private void grisesDescompositionActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        Object seleccion = JOptionPane.showInputDialog(null, 
                "Selecciona: ", null, JOptionPane.QUESTION_MESSAGE, null, 
                new Object[] { "Mínimo", "Máximo"}, "Mínimo");
        int s = -1;
        if (seleccion.equals("Mínimo"))
            s = 0;
        if (seleccion.equals("Máximo"))
            s = 1;
        img.setIcon(new ImageIcon(app.grisesDescomposition(s).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                                    

    private void grisesSingleColorActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        Object seleccion = JOptionPane.showInputDialog(null, 
                "Selecciona color: ", null, JOptionPane.QUESTION_MESSAGE, null, 
                new Object[] { "Rojo", "Verde", "Azul"}, "Rojo");
        int s = -1;
        if (seleccion.equals("Rojo"))
            s = 0;
        if (seleccion.equals("Verde"))
            s = 1;
        if (seleccion.equals("Azul"))
            s = 2;
        img.setIcon(new ImageIcon(app.grisesSingleColor(s).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                                 

    private void grisesShadesActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        int s = sliderShades();
        img.setIcon(new ImageIcon(app.grisesShades(s).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                            

    private void grisesDitheringActionPerformed(java.awt.event.ActionEvent evt) {                                                
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        int s = sliderShades();
        img.setIcon(new ImageIcon(app.grisesDithering(s).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                               

    private void sepiaActionPerformed(java.awt.event.ActionEvent evt) {                                      
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        int s = sliderSepia();
        img.setIcon(new ImageIcon(app.sepia(s).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                     

    private void luzNegraActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        img.setIcon(new ImageIcon(app.blacklight().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                        

    private void mosaicoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        String op = JOptionPane.showInputDialog("Ancho: ");
        int x = Integer.parseInt(op);
        op = JOptionPane.showInputDialog("Altura: ");
        int y = Integer.parseInt(op);
        img.setIcon(new ImageIcon(app.mosaico(x,y).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                       

    private void recursivasActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        String op = JOptionPane.showInputDialog("Ancho: ");
        int x = Integer.parseInt(op);
        op = JOptionPane.showInputDialog("Altura: ");
        int y = Integer.parseInt(op);
        op = JOptionPane.showInputDialog("Nombre del archivo HTML: ");
        try {
            File nuevo = new File("");
            String n = nuevo.getCanonicalPath();
            nuevo = new File(String.format("%s/imagenes", n));
            nuevo.mkdir();
        } catch (IOException e) { }
        String ruta = String.format("imagenes/%s.html", op);
        FileWriter archivo = null;
        PrintWriter pw = null;
        try {
            archivo = new FileWriter(ruta);
            pw = new PrintWriter(archivo);
            pw.println(app.recursiva(x, y));
        } catch (IOException e) {
        } finally {
            try {
                if (null != archivo)
                    archivo.close();
            } catch(IOException e) { }
        }
        abreURL(ruta);
        progreso.setText("Filtro aplicado");
    }                                          

    private void inversoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        img.setIcon(new ImageIcon(app.filtroInverso().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                       

    private void altoContrasteActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        img.setIcon(new ImageIcon(app.altoContraste().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                             

    private void semitonosActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        int s = sliderShades();
        img.setIcon(new ImageIcon(app.semitonos(s).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                         

    private void attActionPerformed(java.awt.event.ActionEvent evt) {                                    
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        img.setIcon(new ImageIcon(app.att().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                   

    private void blendingActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        BufferedImage otra = otra();
        if (imagen.getWidth() != otra.getWidth() || 
                imagen.getHeight() != otra.getHeight()) {
            progreso.setText("La imagen no es del mismo tamaño");
            return;
        }
        img.setIcon(new ImageIcon(app.blending(otra, 0.7).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                        

    private void creadorIconosActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        Object seleccion = JOptionPane.showInputDialog(null, 
                "Selecciona color: ", null, JOptionPane.QUESTION_MESSAGE, null, 
                new Object[] { "16x16", "24x24", "32x32", "48x48", "64x64"}, "16x16");
        int s = -1;
        if (seleccion.equals("16x16"))
            s = 16;
        if (seleccion.equals("32x32"))
            s = 32;
        if (seleccion.equals("48x48"))
            s = 48;
        if (seleccion.equals("64x64"))
            s = 64;
        app.icono(s, s);
        app.guardaIcono();
        progreso.setText("Filtro aplicado");
    }                                             

    private void marcaAguaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        String mensaje = JOptionPane.showInputDialog("Mensaje: ");
        Object region = JOptionPane.showInputDialog(null, "Selecciona región", 
                null, JOptionPane.QUESTION_MESSAGE, null, new Object[] { 
                    "Superior Izquierda", "Superior Derecha", 
                    "Inferior Izquierda", "Inferior Derecha"}, "Superior Izquierda");
        int r = 0;
        if (region.equals("Superior Izquierda"))
            r = App.SUP_IZQ;
        if (region.equals("Superior Derecha"))
            r = App.SUP_DER;
        if (region.equals("Inferior Izquierda"))
            r = App.INF_IZQ;
        if (region.equals("Inferior Derecha"))
            r = App.INF_DER;
        img.setIcon(new ImageIcon(app.marcaAgua(mensaje,r).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                         

    private void rotarActionPerformed(java.awt.event.ActionEvent evt) {                                      
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        int s = JOptionPane.showOptionDialog(null, "Selecciona una opción: ", 
                null, JOptionPane.YES_NO_CANCEL_OPTION, 
                JOptionPane.QUESTION_MESSAGE, null, new Object[] {"0°", 
                    "90°", "180°", "270°"}, "0°");
        int g = s * 90;
        img.setIcon(new ImageIcon(app.rota(g).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                     

    private void sopaLetrasActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        String op = JOptionPane.showInputDialog("Ancho: ");
        int x = Integer.parseInt(op);
        op = JOptionPane.showInputDialog("Altura: ");
        int y = Integer.parseInt(op);
        op = JOptionPane.showInputDialog("Nombre del archivo HTML: ");
        String ruta = String.format("%s.html", op);
        FileWriter archivo = null;
        PrintWriter pw = null;
        try {
            archivo = new FileWriter(ruta);
            pw = new PrintWriter(archivo);
            pw.println(app.sopaLetras(x, y));
        } catch (IOException e) {
        } finally {
            try {
                if (null != archivo)
                    archivo.close();
            } catch(IOException e) { }
        }
        abreURL(ruta);
        progreso.setText("Filtro aplicado");
    }                                          

    private void hombresNegroActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        String op = JOptionPane.showInputDialog("Ancho: ");
        int x = Integer.parseInt(op);
        op = JOptionPane.showInputDialog("Altura: ");
        int y = Integer.parseInt(op);
        op = JOptionPane.showInputDialog("Nombre del archivo HTML: ");
        try {
            File nuevo = new File("");
            String n = nuevo.getCanonicalPath();
            nuevo = new File(String.format("%s/mib", n));
            nuevo.mkdir();
        } catch (IOException e) { }
        String ruta = String.format("mib/%s.html", op);
        FileWriter archivo = null;
        PrintWriter pw = null;
        try {
            archivo = new FileWriter(ruta);
            pw = new PrintWriter(archivo);
            pw.println(app.menInBlack(x, y));
        } catch (IOException e) {
        } finally {
            try {
                if (null != archivo)
                    archivo.close();
            } catch(IOException e) { }
        }
        abreURL(ruta);
        progreso.setText("Filtro aplicado");
    }                                            

    private void recurwscActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        String op = JOptionPane.showInputDialog("Ancho: ");
        int x = Integer.parseInt(op);
        op = JOptionPane.showInputDialog("Altura: ");
        int y = Integer.parseInt(op);
        op = JOptionPane.showInputDialog("Nombre del archivo HTML: ");
        try {
            File nuevo = new File("");
            String n = nuevo.getCanonicalPath();
            nuevo = new File(String.format("%s/imagenes", n));
            nuevo.mkdir();
        } catch (IOException e) { }
        String ruta = String.format("imagenes/%s.html", op);
        FileWriter archivo = null;
        PrintWriter pw = null;
        try {
            archivo = new FileWriter(ruta);
            pw = new PrintWriter(archivo);
            pw.println(app.recursivaWSC(x, y));
        } catch (IOException e) {
        } finally {
            try {
                if (null != archivo)
                    archivo.close();
            } catch(IOException e) { }
        }
        abreURL(ruta);
        progreso.setText("Filtro aplicado");
    }                                        

    private void bordeActionPerformed(java.awt.event.ActionEvent evt) {                                      
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        img.setIcon(new ImageIcon(app.borde().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                     

    private void sharpenActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        img.setIcon(new ImageIcon(app.sharpen().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                       

    private void blurActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        img.setIcon(new ImageIcon(app.blur().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                    

    private void motionblurActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        img.setIcon(new ImageIcon(app.motionBlur().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                          

    private void promedioActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        img.setIcon(new ImageIcon(app.promedio().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                        

    private void mediaActionPerformed(java.awt.event.ActionEvent evt) {                                      
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        double[][] filter = {{1,1,1},{1,1,1},{1,1,1}};
        img.setIcon(new ImageIcon(app.media(filter).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                     

    private void oleobnActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        app.grisesAverage();
        img.setIcon(new ImageIcon(app.oleo().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                      

    private void oleocolorActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        img.setIcon(new ImageIcon(app.oleo().getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                         

    private void fotomosaicosActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        String op = JOptionPane.showInputDialog("Ancho: ");
        int x = Integer.parseInt(op);
        op = JOptionPane.showInputDialog("Altura: ");
        int y = Integer.parseInt(op);
        File carpeta = new File("");
        JFileChooser selector = new JFileChooser();
        selector.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int aux = selector.showOpenDialog(null);
        if (aux == JFileChooser.APPROVE_OPTION) {
            carpeta = selector.getSelectedFile();
        }
        String ruta = carpeta.getPath();
        op = JOptionPane.showInputDialog("Nombre del archivo HTML: ");
        ruta = String.format("%s/%s.html", ruta, op);
        FileWriter archivo = null;
        PrintWriter pw = null;
        try {
            archivo = new FileWriter(ruta);
            pw = new PrintWriter(archivo);
            pw.println(app.fotoMosaicos(x, y, carpeta));
        } catch (IOException e) {
        } finally {
            try {
                if (null != archivo)
                    archivo.close();
            } catch(IOException e) { }
        }
        abreURL(ruta);
        progreso.setText("Filtro aplicado");
    }                                            

    private void reduccionActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        int s = sliderReduccion();
        int x = 0;
        int y = 0;
        System.out.println(s);
        if (s != 0) {
            x = imagen.getWidth() / (100 / s);
            y = imagen.getHeight() / (100 / s);
        }
        img.setIcon(new ImageIcon(app.amplia(x,y).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                         

    private void ampliacionActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        int s = sliderReduccion();
        int x = 0;
        int y = 0;
        System.out.println(s);
        if (s != 0) {
            x = imagen.getWidth() * (100 / s);
            y = imagen.getHeight() * (100 / s);
        }
        img.setIcon(new ImageIcon(app.amplia(x,y).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                          

    private void losselessActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        String op = JOptionPane.showInputDialog("Nombre del archivo binario: ");
        String ruta = String.format("%s.data", op);
        app.comprimeLosseless(ruta);
        progreso.setText("Filtro aplicado");
    }                                         

    private void rotamatActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        int s = JOptionPane.showOptionDialog(null, "Selecciona una opción: ", 
                null, JOptionPane.YES_NO_CANCEL_OPTION, 
                JOptionPane.QUESTION_MESSAGE, null, new Object[] {"0°", 
                    "90°", "180°", "270°"}, "0°");
        int g = s * 90;
        img.setIcon(new ImageIcon(app.rotaMatriz(g).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                       

    private void descompresiónActionPerformed(java.awt.event.ActionEvent evt) {                                              
        progreso.setText("Procesando...");
        File file = archivo();
        img.setIcon(new ImageIcon(app.descomprime(file).getScaledInstance(
                img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("Filtro aplicado");
    }                                             

    private void lossyActionPerformed(java.awt.event.ActionEvent evt) {                                      
        if (imagen == null)
            return;
        progreso.setText("Procesando...");
        String op = JOptionPane.showInputDialog("Nombre del archivo binario: ");
        String ruta = String.format("%s.data", op);
        Object seleccion = JOptionPane.showInputDialog(null, 
                "Selecciona color: ", null, JOptionPane.QUESTION_MESSAGE, null, 
                new Object[] { "Rojo", "Verde", "Azul"}, "Rojo");
        int s = -1;
        if (seleccion.equals("Rojo"))
            s = 0;
        if (seleccion.equals("Verde"))
            s = 1;
        if (seleccion.equals("Azul"))
            s = 2;
        app.comprimeLossy(ruta, s);
        progreso.setText("Filtro aplicado");
    }                                     

    /* AUXILIAR PARA REINICIAR LA IMAGEN. */
    private void reinicia() {
        copia = app.copia();
        img.setIcon(new ImageIcon(copia.getScaledInstance(img.getWidth(), 
                img.getHeight(), Image.SCALE_DEFAULT)));
        progreso.setText("");
    }
    
    /* SLIDER PARA COLORES R, G Y B. */
    private int sliderRGB(String color) {
        JFrame parent = new JFrame();
        JOptionPane op = new JOptionPane();
        JSlider slider = getSlider(op, 0, 255, 51);
        op.setMessage(new Object[] {color, slider});
        op.setMessageType(JOptionPane.QUESTION_MESSAGE);
        op.setOptionType(JOptionPane.OK_CANCEL_OPTION);
        JDialog dialog = op.createDialog(parent, color);
        dialog.setVisible(true);
        return (int)op.getInputValue();
    }
    
    /* SLIDER PARA BRILLO. */
    private int sliderBrillo() {
        JFrame parent = new JFrame();
        JOptionPane op = new JOptionPane();
        JSlider slider = getSlider(op, -255, 255, 101);
        op.setMessage(new Object[] {"Brillo: ", slider});
        op.setMessageType(JOptionPane.QUESTION_MESSAGE);
        op.setOptionType(JOptionPane.OK_CANCEL_OPTION);
        JDialog dialog = op.createDialog(parent, "Brillo");
        dialog.setVisible(true);
        return (int)op.getInputValue();
    }
    
    /* SLIDER PARA SOMBRAS. */
    private int sliderShades() {
        JFrame parent = new JFrame();
        JOptionPane op = new JOptionPane();
        JSlider slider = getSlider(op, 2, 256, 101);
        op.setMessage(new Object[] {"Sombra: ", slider});
        op.setMessageType(JOptionPane.QUESTION_MESSAGE);
        op.setOptionType(JOptionPane.OK_CANCEL_OPTION);
        JDialog dialog = op.createDialog(parent, "Sombras");
        dialog.setVisible(true);
        return (int)op.getInputValue();
    }
    
    /* SLIDER PARA SEPIA. */
    private int sliderSepia() {
        JFrame parent = new JFrame();
        JOptionPane op = new JOptionPane();
        JSlider slider = getSlider(op, 1, 255, 51);
        op.setMessage(new Object[] {"Amarillo: ", slider});
        op.setMessageType(JOptionPane.QUESTION_MESSAGE);
        op.setOptionType(JOptionPane.OK_CANCEL_OPTION);
        JDialog dialog = op.createDialog(parent, "Amarillos");
        dialog.setVisible(true);
        return (int)op.getInputValue();
    }
    
    /* SLIDER PARA REDUCCIÓN DE IMÁGENES. */
    private int sliderReduccion() {
        JFrame parent = new JFrame();
        JOptionPane op = new JOptionPane();
        JSlider slider = getSlider(op, 0, 100, 25);
        slider.setValue(0);
        op.setMessage(new Object[] {"Porcentaje: ", slider});
        op.setMessageType(JOptionPane.QUESTION_MESSAGE);
        op.setOptionType(JOptionPane.OK_CANCEL_OPTION);
        JDialog dialog = op.createDialog(parent, "Porcentajes");
        dialog.setVisible(true);
        return (int)op.getInputValue();
    }
    
    /* AUXILIAR PARA CREAR SLIDERS. */
    private JSlider getSlider(final JOptionPane op, int min, int max, int esp) {
        JSlider slider = new JSlider(min, max);
        slider.setMajorTickSpacing(esp);
        slider.setPaintTicks(true);
        slider.setPaintLabels(true);
        ChangeListener changeListener = new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent ce) {
                JSlider sldr = (JSlider)ce.getSource();
                if (!sldr.getValueIsAdjusting())
                    op.setInputValue(sldr.getValue());
            }
        };
        slider.addChangeListener(changeListener);
        return slider;
    }
    
    /* AUXILIAR PARA ABRIR UN HTML. */
    private void abreURL(String url) {
        String osName = System.getProperty("os.name");
        try {
            if (osName.startsWith("Windows"))
                Runtime.getRuntime().exec(
                        "rundll32 url.dll,FileProtocolHandler " + url);
            else if (osName.startsWith("Mac OS X"))
                Runtime.getRuntime().exec("open" + url);
            else
                Runtime.getRuntime().exec("google-chrome " + url);
        } catch (IOException e) {
            System.out.println("Error al abrir el explorador.");
        }
    }
    
    /* AUXILIAR PARA ESCOGER OTRA IMAGEN. */
    private BufferedImage otra() {
        JFileChooser selector = new JFileChooser();
        selector.setDialogTitle("Selecciona una imagen");
        FileNameExtensionFilter filtro =
                new FileNameExtensionFilter("jpg, jpeg, bmp, png", "jpg", 
                        "jpeg", "bmp", "png");
        selector.setFileFilter(filtro);
        int aux = selector.showOpenDialog(null);
        BufferedImage otra = null;
        if (aux == JFileChooser.APPROVE_OPTION) {
            try {
                File file = selector.getSelectedFile();
                otra = ImageIO.read(file);
            } catch (IOException e) { }
        }
        return otra;
    }
    
    /* AUXILIAR PARA ESCOGER UN ARCHIVO. */
    private File archivo() {
        JFileChooser selector = new JFileChooser();
        selector.setDialogTitle("Selecciona una imagen");
        FileNameExtensionFilter filtro =
                new FileNameExtensionFilter("data", "data");
        selector.setFileFilter(filtro);
        int aux = selector.showOpenDialog(null);
        File file = null;
        if (aux == JFileChooser.APPROVE_OPTION) {
            file = selector.getSelectedFile();
        }
        return file;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem abrir;
    private javax.swing.JMenuItem altoContraste;
    private javax.swing.JMenuItem ampliacion;
    private javax.swing.JMenuItem att;
    private javax.swing.JMenuItem azar;
    private javax.swing.JMenuItem azul;
    private javax.swing.JMenuItem blending;
    private javax.swing.JMenuItem blur;
    private javax.swing.JMenuItem borde;
    private javax.swing.JMenuItem brillo;
    private javax.swing.JMenuItem creadorIconos;
    private javax.swing.JMenuItem descompresión;
    private javax.swing.JMenuItem favicon;
    private javax.swing.JMenuItem fotomosaicos;
    private javax.swing.JMenuItem grisesDesaturation;
    private javax.swing.JMenuItem grisesDescomposition;
    private javax.swing.JMenuItem grisesDithering;
    private javax.swing.JMenuItem grisesLuma;
    private javax.swing.JMenuItem grisesPromedio;
    private javax.swing.JMenuItem grisesShades;
    private javax.swing.JMenuItem grisesSingleColor;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JMenuItem hombresNegro;
    private javax.swing.JLabel img;
    private javax.swing.JMenuItem inverso;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem losseless;
    private javax.swing.JMenuItem lossy;
    private javax.swing.JMenuItem luzNegra;
    private javax.swing.JMenuItem marcaAgua;
    private javax.swing.JMenuItem media;
    private javax.swing.JMenu menu_ajusteDeColor;
    private javax.swing.JMenu menu_archivo;
    private javax.swing.JMenu menu_artisticos;
    private javax.swing.JMenu menu_combinar;
    private javax.swing.JMenu menu_contrastes;
    private javax.swing.JMenu menu_iconos;
    private javax.swing.JMenu menu_marcaAgua;
    private javax.swing.JMenu menu_mosaicos;
    private javax.swing.JMenu menu_rotar;
    private javax.swing.JMenuItem mosaico;
    private javax.swing.JMenuItem motionblur;
    private javax.swing.JMenuItem oleobn;
    private javax.swing.JMenuItem oleocolor;
    private javax.swing.JTextField progreso;
    private javax.swing.JMenuItem promedio;
    private javax.swing.JMenuItem recursivas;
    private javax.swing.JMenuItem recurwsc;
    private javax.swing.JMenuItem reduccion;
    private javax.swing.JMenuItem reiniciar;
    private javax.swing.JMenuItem rgb;
    private javax.swing.JMenuItem rojo;
    private javax.swing.JMenuItem rotamat;
    private javax.swing.JMenuItem rotar;
    private javax.swing.JMenuItem semitonos;
    private javax.swing.JMenuItem sepia;
    private javax.swing.JMenuItem sharpen;
    private javax.swing.JMenuItem sopaLetras;
    private javax.swing.JMenuItem verde;
    // End of variables declaration                   
}

    /**
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    */